[theme]
primaryColor = "#2E8B57"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#E3E8EF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
